numarul1:
    min: 4
    max: 100
    type: int

numarul2:
    min: 5
    max: 30
    type: float
    precision: 1


F1:
    funct: 'lambda a, b : [a + b * a]'
    variables: [numarul1, numarul2]
    returns: [rez]
    precision: 3


Hidden: [rez]