numarul1:
    min: 15
    max: 70
    type: int

numarul2:
    min: 5
    max: 12
    type: float
    precision: 3


F1:
    funct: 'lambda a, b : [(a+b)/2 , a - b]'
    variables: [numarul1, numarul2]
    returns: [medie, diferenta]
    precision: 3


Hidden: [medie, diferenta]